mp3:gui_mp3.c
	gcc -o pc_gui_mp3 gui_mp3.c -lpthread -lminigui
	arm-linux-gcc -o arm_gui_mp3 gui_mp3.c -lpthread -lminigui
	#arm-linux-gcc -o arm_led led.c
clean:
	rm -rf pc_gui_mp3 arm_gui_mp3 *~ 
	
