#! /bin/sh



/bin/echo
/bin/echo "**********************************************"
/bin/echo "   SEP4020 ARM Linux-2.6.16 SDK 3.1     "
/bin/echo "**********************************************"


echo "# mount all..........."

/bin/mount -a

echo "# Starting mdev........."

mdev -s



