#
# Makefile for the sep4020 character device drivers.
#
obj-$(CONFIG_SEP4020_PSAM) += sep4020_psam.o
obj-$(CONFIG_SEP4020_KEY) += sep4020_key.o
obj-$(CONFIG_SEP4020_LED) += sep4020_led.o
obj-$(CONFIG_SEP4020_RTC) += sep4020_rtc.o
obj-$(CONFIG_SEP4020_PRINTER) += thermal_printer.o 
obj-$(CONFIG_SEP4020_TP) += sep4020_tp.o
obj-$(CONFIG_SEP4020_MGCD) += sep4020_mgcard.o
obj-$(CONFIG_SEP4020_PRINTER2) += sep4020_printer.o
